# Generated by Django 4.1.5 on 2023-01-03 15:05

import autoslug.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'hidden'), (1, 'Public'), (2, 'coming soon')], default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('repo_url',))),
                ('hosted_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('screenshot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('completion_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
